config/routes.rb
Blog::Application.routes.draw do
	root :to => 'articles#index'
  	get "tags/index"
  	get "tags/show"
	resources :comments
  resources :articles
  resources :tags
  resources :user_sessions,
  		only: [ :new, :create, :destroy ]
	resources :users
  resources :password_resets
	get 'login' => 'user_sessions#new', :as => :login
	post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/article.rb
class Article < ActiveRecord::Base
	attr_accessible :title, :body, :author, :tag_list, :image
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings
	has_many :attachments
	has_attached_file :image

	def tag_list
		self.tags.collect do |tag|
		tag.name
		end.join(", ")
	end

	def publish_month
	  created_at.strftime("%B %Y")
	end
	
	def tag_list=(tags_string)
		self.taggings.destroy_all
		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
		
		tag_names.each do |tag_name|
			tag = Tag.find_or_create_by_name(tag_name)
			tagging = self.taggings.new
			tagging.tag_id = tag.id
		end
	end

	def to_s
		name
	end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
	  attr_accessible :article_id,  :image
  belongs_to :article
has_attached_file :image,
    :styles => {
      :thumb=> "100x100#",
      :small  => "300x300>",
      :large => "600x600>"
        }
end

app/models/comment.rb
class Comment < ActiveRecord::Base 
	attr_accessible :article_id, :author_name, :body
	belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	attr_accessible :name
	has_many :taggings, dependent: :destroy
	has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
	attr_accessible :article_id, :tag_id
	belongs_to :article
	belongs_to :tag

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
attr_accessible :email, :password, :password_confirmation 
  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	# Prevent CSRF attacks by raising an exception.
  	# For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception
  	before_filter :require_login

  	private
	def not_authenticated
	  redirect_to login_path, alert: "Please login first"
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_filter :require_login, except: [:index, :show]
	def index 
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id = @article.id
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(
		 title: params[:article][:title],
		 body: params[:article][:body],
		 author: params[:article][:author])
		@article.save
		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
	end

	def edit
 		@article = Article.find(params[:id])
	end

	def update
 		@article = Article.find(params[:id])
 		@article.update_attributes(params[:article])
 		redirect_to article_path(@article)
 		flash.notice = "Article '#{@article.title}' Updated!"
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :require_login, except: [:create]
	def create
		article_id = params[:comment] .delete(:article_id)
		@comment = Comment.new(params[:comment])
		@comment.article_id = article_id
		@comment.save
		redirect_to article_path(@comment.article)
	end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_filter :require_login

  # request password reset.
  # you get here when the user entered his email in the reset password form and submitted it.
  def create 
    @user = User.find_by_email(params[:email])

    # This line sends an email to the user with instructions on how to reset their password (a url with a random token)
    @user.deliver_reset_password_instructions! if @user

    # Tell the user instructions have been sent whether or not email was found.
    # This is to not leak information to attackers about which emails exist in the system.
    redirect_to(root_path, :notice => 'Instructions have been sent to your email.')
  end

  # This is the reset password form.
  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end
  end

  # This action fires when the user has sent the reset password form.
  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end

    # the next line makes the password confirmation validation work
    @user.password_confirmation = params[:user][:password_confirmation]
    # the next line clears the temporary token and updates the password
    if @user.change_password!(params[:user][:password])
      redirect_to(root_path, :notice => 'Password was successfully updated.')
    else
      render :action => "edit"
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  	before_filter :require_login, only: [:destroy]
  	def index
  		@tags = Tag.all
  	end

  	def show
		@tag = Tag.find(params[:id])
	end

 	def destroy
	  	@tag = Tag.find(params[:id])
	  	@Tag.destroy
	end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
    skip_before_filter :require_login, except: [:destroy]
    
    def new
      @user = User.new
    end

    def create
      if @user = login(params[:email], params[:password])
        redirect_back_or_to(articles_path, notice: 'Login successful')
      else
        flash.now[:alert] = 'Login failed'
        render action: 'new'
      end
    end

    def destroy
      logout
      redirect_to(articles_path, notice: 'Logged out!')
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, only: [:index, :new, :create]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

	def tag_links(tags)
	 	links = tags.collect{|tag| link_to tag.name, tag_path(tag)}
	 	return links.join(", ").html_safe
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_comment.html.erb
<div class="comment">
	 <h4>Comment by <%= comment.author_name %></h4>
	 <p><%= comment.body %></p>
	 <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> ago
	</p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
 <ul>
 <% @article.errors.full_messages.each do |error| %>
 <li><%= error %></li>
 <% end %>
 </ul>
 <p>
 <%= f.label :title %><br />
 <%= f.text_field :title %>
 </p>
 <p>
 <%= f.label :body %><br />
 <%= f.text_area :body %>
 </p>
 <p>
 <%= f.label :author %><br />
 <%= f.text_field :author %>
 </p>
 <p>
 <%= f.label :tag_list %><br />
 <%= f.text_field :tag_list %>
</p>
<p>
 <% if @article.image.exists? %>
 <%= image_tag @article.image.url %><br/>
 <% end %>
 <%= f.label :image, "Attach a New Image" %><br />
 <%= f.file_field :image %>
</p>
 <p>
 <%= f.submit %>
 </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit a Article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul>
	<% @articles.each do |article| %>
	<li>
		<%= link_to article.title, article_path(article) %>
		<% article.tags %>
	</li>
	<% end %>
	<% if logged_in? %>
	<li><%= link_to "create a new article",new_article_path, class: "new_article"%></li>
	<% end -%>
</ul>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<h3><%= @article.author %></h3>
<p>Tags: <%= tag_links(@article.tags) %></p>
<p><%= @article.body %></p>
 <% if @article.image.exists? %>
	<p><%= image_tag @article.image.url(:medium) %></p>
 <% end %>

<h3>Comments (<%= @article.comments.size %>)</h3>
<%= render partial: 'comment', collection: @article.comments.reverse, :locals => { :list => true } %>
<%= render partial: 'comments/form' %>

<%= link_to "Back To List", articles_path %>
<% if logged_in? %>
<%= link_to "delete", article_path(@article), method: :delete, confirm: "Really delete the article?"%>
<%= link_to "edit", edit_article_path(@article) %>
<% end -%>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>
<%= form_for @comment do |f| %>
 <%= f.hidden_field :article_id %>
 <p>
 <%= f.label :author_name , "Your Name"%><br/>
 <%= f.text_field :author_name %>
 </p>
 <p>
 <%= f.label :body , "Your Comment"%><br/>
 <%= f.text_area :body %>
 </p>
 <p>
 <%= f.submit 'Submit' %>
 </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  	<head>
	  	<meta charset="utf-8" />

	  	<!-- Uncomment to make IE8 render like IE7 -->
	  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

	  	<!-- Set the viewport width to device width for mobile -->
	  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	  	<title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>

	  	<%= stylesheet_link_tag    "application" %>
	  	<%= javascript_include_tag "vendor/custom.modernizr" %>
	    <%= csrf_meta_tags %>
	</head>
	<body>
		<nav class="top-bar">
	  		<ul class="title-area">
	    		<li class="name">
	     			<h1><%= link_to "Rails Blog", articles_path %></a></h1>
	    		</li>
	  		</ul>
	  		<section class="top-bar-section">
	    		<ul class="right">
			      <li class="divider"></li>
			      <li><%= link_to "Home", articles_path %></li>
			      <li class="divider"></li>
			      <li><%= link_to "Contact Us" %></li>
		      	    <% if current_user %>
		      	    	<li class="divider"></li>
				      	<li><%= link_to "Edit Profile", edit_user_path(current_user.id) %></li>
				      	<li class="divider"></li>
				      	<li><%= link_to "Logout", :logout, method: :post %></li>
				    <% else %>
				    	<li class="divider"></li>
				      	<li><%= link_to "Register", new_user_path %></li>
				      	<li class="divider"></li>
				      	<li><%= link_to "Login", :login %></li>
				    <% end %>
	    		</ul>
	 		</section>
		</nav>
			 		<!--<div class="icon-bar five-up" role="navigation">
					  <a class="item" role="button" tabindex="0" aria-label="home">
					    <i class="fi-home"></i>
					  </a>
					  <a class="item" role="button" tabindex="0" aria-label="Bookmark">
					    <i class="fi-bookmark"></i>
					  </a>
					  <a class="item" role="button" tabindex="0" aria-label="Information">
					    <i class="fi-info"></i>
					  </a>
					  <a class="item" role="button" tabindex="0" aria-label="Mail">
					    <i class="fi-mail"></i>
					  </a>
					  <a class="item" role="button" tabindex="0" aria-label="Like">
					    <i class="fi-like"></i>
					  </a>
					</div>-->
		<div class="row">
			<div class="small-8 columns">	  
			  	<div>
				    <p id="notice"><%= flash[:notice] %></p>
				    <p id="alert"><%= flash[:alert] %></p>
				</div>
				<%= yield %>
			</div>
		  	<div class="small-4 columns">
			    <h2 class="subheader">About Us</h2>
			    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		  	</div>
		</div>
	    <%= javascript_include_tag "application" %>
	</body>
</html>

app/views/password_resets/create.html.erb
<h1>PasswordResets#create</h1>
<p>Find me in app/views/password_resets/create.html.erb</p>

app/views/password_resets/edit.html.erb
<h1>Choose a new password</h1>
<%= form_for @user, :url => password_reset_path(@token), :html => {:method => :put} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= @user.email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/password_resets/update.html.erb
<h1>PasswordResets#update</h1>
<p>Find me in app/views/password_resets/update.html.erb</p>

app/views/tags/index.html.erb
<h1>Tag index</h1>
<p>List of tags currently in use</p>

<table>
	<ul>
		<% cur_letter = nil %>
		<% @tags.each do |t| %>
	  		<% tag_letter = t.name[0].capitalize.match(/[A-Z]/) ? t.name[0].capitalize : "#" %> 
	  		<% if tag_letter != cur_letter %>
	    		<% cur_letter = tag_letter %>
	    		<li>
	    			<b><%= cur_letter %></b>
				</li>
	  		<% end %>
			<p><%= t.name%>: 
				<% t.articles.each do |t| %> 
					<%= link_to t.title, articles_path(t) %>
				<% end %> 
			</p>
		<% end %>
	</ul>
</table>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>
<ul>
 <% @tag.articles.each do |article| %>
 <li><%= link_to article.title, article_path(article) %></li>
 <% end %>
</ul>

app/views/user_sessions/_forgot_password_form.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %> <%= submit_tag "Reset my password!" %>
  </div>
<% end %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>
<%= link_to 'Back', articles_path %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>
<%= link_to 'Back', articles_path %>


<h1>Forgot Password?</h1>
<%= render 'forgot_password_form' %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Crypted password</th>
      <th>Salt</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.crypted_password %></td>
        <td><%= user.salt %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Crypted password:</strong>
  <%= @user.crypted_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>